# Generated by Django 5.1.1 on 2024-09-08 18:07

import helpers.timestampedmodel
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'breakfast'), ('BRUNCH', 'brunch'), ('LUNCH', 'lunch'), ('LUPPER', 'lupper'), ('SUPPER', 'supper'), ('DINNER', 'dinner')], default=None, max_length=128, null=True)),
                ('name', models.CharField(max_length=256)),
                ('discount', models.FloatField(default=0.0)),
            ],
            bases=(models.Model, helpers.timestampedmodel.TimeStampedModelMixin),
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('registration', models.CharField(max_length=256)),
                ('location', models.TextField(max_length=1024)),
                ('latitude', models.FloatField(max_length=100)),
                ('longitude', models.FloatField(max_length=200)),
                ('inagurated', models.DateField()),
                ('opens_at', models.DateField()),
                ('closes_at', models.DateField()),
            ],
            bases=(models.Model, helpers.timestampedmodel.TimeStampedModelMixin),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('discount', models.FloatField(default=0.0)),
            ],
            bases=(models.Model, helpers.timestampedmodel.TimeStampedModelMixin),
        ),
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('price', models.FloatField(default=0.0)),
                ('discount', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('AVAILABLE', 'available'), ('OUTOFSTOCK', 'outofstock')], default='AVAILABLE', max_length=256)),
            ],
            bases=(models.Model, helpers.timestampedmodel.TimeStampedModelMixin),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=1024)),
                ('price', models.FloatField(default=0.0)),
                ('discount', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('AVAILABLE', 'available'), ('OUTOFSTOCK', 'outofstock')], default='AVAILABLE', max_length=255)),
                ('categories', models.ManyToManyField(related_name='items', to='kitchen.category')),
            ],
            bases=(models.Model, helpers.timestampedmodel.TimeStampedModelMixin),
        ),
    ]
