# Generated by Django 5.1.1 on 2024-09-08 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kitchen', '0001_initial'),
        ('stakeholders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchens', to='stakeholders.owner'),
        ),
        migrations.AddField(
            model_name='item',
            name='menus',
            field=models.ManyToManyField(related_name='items', to='kitchen.menu'),
        ),
        migrations.AddField(
            model_name='modifier',
            name='items',
            field=models.ManyToManyField(related_name='modifiers', to='kitchen.item'),
        ),
    ]
