# Generated by Django 5.1.1 on 2024-09-07 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0002_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stakeholders.user',),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stakeholders.user',),
        ),
    ]
