# Generated by Django 5.1.1 on 2024-09-07 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0003_employee_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stakeholders.user',),
        ),
    ]
